### ISSUE TITLE
Add the link to the notebook instead of the html file in the README

### ISSUE THREAD

**Issue by AMR-KELEG** [AhmedAbdel-Aal/Arabic-poem-Generator#1]
Github can render Python Notebooks so it would be better if you update the link in the README to the notebook instead of the html file.
I liked the project but I am not a fan of Generative models so I am hesitant about the generated poems.
`فَأَنتَ المُنكِرَت أَنتَ`
أنا مش منكرت لا :smile: 
Good Luck :smile:

**Comment by AhmedAbdel-Aal** [comment]
Yes, thanks for this hint i will do that 😄 

i am willing to make a better model, the thing is the data used for training was chosen randomly from different kind of poem category so sometimes it generates kind of شعر حديث  and other times it be more like شعر جاهلي 

however i added another source for the poetry data, you could do better 😃
